Repository jef/streetmerchant, pull requests merged in 2020-10, with the labels that each got.

#455 feat: add uk stores
  README.md
  src/index.ts
  src/store/fetch-links.ts
  src/store/lookup.ts
  src/store/model/amazon-uk.ts
  src/store/model/aria.ts
  src/store/model/box.ts
  src/store/model/ccl.ts
  src/store/model/currys.ts
  src/store/model/ebuyer.ts
  src/store/model/helpers/card.ts
  src/store/model/index.ts
  src/store/model/novatech.ts
  src/store/model/overclockers.ts
  src/store/model/scan.ts
  src/store/model/store.ts
  src/store/model/very.ts
Labels: type: enhancement

#411 feat(docker): add docker and publish images to ghcr
  .dockerignore
  .env-example
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  Dockerfile
  README.md
  src/config.ts
  src/index.ts
Labels: status: needs discussion

#486 chore: add typescript definitions for custom types
  src/config.ts
  src/index.ts
  src/notification/pushover.ts
  src/notification/sound.ts
  src/types/play-sound.d.ts
  src/types/puppeteer-extra-plugin-block-resources.d.ts
  src/types/pushbullet.d.ts
  src/types/pushover-notifications.d.ts
Labels: type: chore, type: enhancement
