Repository jef/streetmerchant, pull requests merged in 2020-09, with the labels that each got.

#214 feat(store): add zotac store
  src/store/model/index.ts
  src/store/model/zotac.ts
Labels: ready for merge

#180 chore(store): add errors for bandh
  src/store/model/bandh.ts
Labels: ready for merge

#172 feat(store): add evga eu
  README.md
  src/store/model/evga-eu.ts
  src/store/model/index.ts
Labels: ready for merge

#201 fix(store): bandh removed cards
  src/store/model/bandh.ts
Labels: ready for merge

#206 chore(store): strix on amazon
  src/store/model/amazon.ts
Labels: ready for merge

#210 chore(store): add netherland nvidia
  README.md
  src/store/model/nvidia.ts
Labels: ready for merge

#209 feat: add chromium sandbox skipping
  .env-example
  README.md
  src/config.ts
  src/index.ts
Labels: ready for merge

#347 feat: retry logic for nvidia session token and adding to cart
  .env-example
  README.md
  src/config.ts
  src/store/model/helpers/nvidia-cart.ts
  src/store/model/helpers/nvidia.ts
  src/store/model/nvidia-api.ts
Labels: enhancement

#346 fix(notification): discord false triggers
  src/notification/notification.ts
Labels: bug

#339 docs: update supported countries
  README.md
Labels: docs

#356 fix: corrected norway locales
  src/store/model/nvidia-api.ts
Labels: bug

#364 fix: `envOrNumber` behavior
  src/config.ts
Labels: bug

#340 feat: configurable status code behaviours
  src/logger.ts
  src/store/lookup.ts
  src/store/model/asus.ts
  src/store/model/helpers/backoff.ts
  src/store/model/store.ts
  src/store/model/zotac.ts
  src/util.ts
Labels: bug, enhancement

#361 fix: remove 3090 drid for DK/FI regions
  README.md
  src/store/model/nvidia-api.ts
Labels: bug
